---
- name: setup nodejs sources
  shell: bash -lc "curl -sL https://deb.nodesource.com/setup_6.x | bash -"

- name: install nodejs
  apt: name={{ item }} state=installed
  with_items:
    - nodejs
    - gcc-c++
    - make
