---
- name: install apt-transport-https
  apt: pkg=apt-transport-https state=present

- name: add nodesource package signing key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add nodesource solutions repo
  apt_repository: repo='deb https://deb.nodesource.com/node_6.x jessie main'

- name: add nodesource solutions src repo
  apt_repository: repo='deb-src https://deb.nodesource.com/node_6.x jessie main'

- name: install nodejs
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nodejs
